"""Regression tests for the feature/loader-12340 updater-only TEST wiring."""
import json
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

class EpochUpdaterTests(unittest.TestCase):
    def test_updater_build_compiles_explicit_epoch_feature(self):
        wf=(ROOT/".github/workflows/build_updater.yml").read_text(encoding="utf-8")
        ui=(ROOT/"tools/updater/Updater335Dashboard.cs").read_text(encoding="utf-8")
        app=(ROOT/"tools/updater/WoW335Updater.cs").read_text(encoding="utf-8")
        feature=(ROOT/"tools/updater/UpdaterEpochLoaderFeature.cs").read_text(encoding="utf-8")
        self.assertIn("feature/loader-12340",wf)
        self.assertIn("src/Loader12340/**",wf)
        self.assertIn("runtime/epoch_loader_interop.json",wf)
        maintenance=(ROOT/"tools/updater/UpdaterMaintenanceFeature.cs").read_text(encoding="utf-8")
        self.assertIn('UpdaterBuildInfo.Version.EndsWith("-epoch-test"',maintenance)
        self.assertIn('"feature/loader-12340"',maintenance)
        self.assertIn("UpdaterEpochLoaderFeature.cs",wf)
        # Core UI is exactly three actions; TEST install and rollback stay in
        # managed code rather than separate visible buttons.
        self.assertEqual(ui.count("actions.Controls.Add(UiButton("),3)
        for label in ('"Sprawdź"', '"Aktualizuj"', '"Aktualizuj i uruchom"'):
            self.assertIn(label,ui)
        for old in ('Epoch Loader TEST', 'Aktywne DLL / kolejność',
                    'Przywróć Epoch DLL', 'Instaluj test AutoLoot',
                    'Natywny AutoLoot TEST', '"Rollback"', '"Uruchom grę"'):
            self.assertNotIn(old,ui)
        self.assertIn('UseEpochTestFlow()',app)
        self.assertIn('return await EpochInstallAsync()',app)
        self.assertIn('var latest = await EpochLatestAsync();',app)
        self.assertIn('if (await UpdateAsync())',app)
        self.assertIn('private async Task<bool> EpochInstallAsync()',feature)
        self.assertIn('private async Task<Tuple<string, long>> EpochLatestAsync()',feature)
        self.assertIn('EpochValidateLaunch(root);',app)
        self.assertIn("EpochValidateLaunch(root);",app)
        self.assertIn("EpochBranch = \"feature/loader-12340\"",feature)
        self.assertIn("UpdaterSafety.RequireLatestSuccessfulRun",feature)
        self.assertIn("EpochOriginalSha",feature)
        self.assertIn("EpochCheckFile",feature)
        self.assertIn("EpochRollback()",feature)
        self.assertIn("test_pair_gate",feature)
        self.assertIn("module_load_order",feature)
        self.assertIn("EpochExistingManagedOrder",feature)
        self.assertIn("EpochWorkAutoLootCommit",feature)
        self.assertIn("EpochWorkAutoLootSha",feature)
        safety=(ROOT/"tools/updater/UpdaterSafety.cs").read_text(encoding="utf-8")
        self.assertIn("public static bool IsGitCommitSha(string value)",safety)
        self.assertIn("value.Length != 40",safety)
        self.assertIn('UpdaterSafety.IsGitCommitSha(GetString(state, "git_sha"))',feature)
        self.assertIn("UpdaterSafety.IsGitCommitSha(sha)",feature)
        self.assertNotIn("UpdaterSafety.IsSha256Hex(sha)",feature)
        self.assertNotIn('UpdaterSafety.IsSha256Hex(GetString(state, "git_sha"))',feature)
        self.assertIn('UpdaterSafety.IsSha256Hex(GetString(state, "epoch_sha256"))',feature)
        self.assertIn("GitShaSmoke.cs",wf)
        self.assertIn("GIT_SHA_VALIDATION_SMOKE: PASS",wf)
        interop=json.loads((ROOT/"runtime/epoch_loader_interop.json").read_text(encoding="utf-8"))
        self.assertEqual(interop["source"]["commit"],"f1372bfa30f9fbe62fe8e10e8de444ae38bc406e")
        self.assertEqual(interop["source"]["sha256"],"e2bf85df42ca8c434db5a99a7606a7d3cf82995ea525fa8acec2c8cc7587579a")
        self.assertEqual(interop["compatibility"],"not_verified_in_game")
        self.assertIn(interop["source"]["commit"],feature)
        self.assertIn(interop["source"]["sha256"],feature)
        self.assertIn("managed_sha256",feature)
        self.assertIn('GetValue(state, "managed_sha256")',feature)
        self.assertIn('hashValue as Dictionary<string, object>',feature)
        self.assertIn('35855470746L',feature)
        self.assertIn('EpochCheckFile(target, EpochFrameAutoLootSha)',feature)
        self.assertIn('EpochFrameAutoLootArtifact',feature)
        self.assertIn('EpochFrameAutoLootRunId',feature)
        self.assertIn('origin_artifact_kind',feature)
        self.assertIn('FRAME_ARMED',loader)
        self.assertIn('string stage = "wstępna kontrola lokalnych plików"',feature)
        self.assertIn('"Etap: " + stage',feature)
        self.assertIn('"artifact_name"',feature)
        self.assertIn("EpochCheckFile(Path.Combine(root, EpochWorkAutoLoot)",feature)
        self.assertIn("EpochUpgradeAutoLoot(root, activeOrder)",feature)
        self.assertIn("EpochApprovedAutoLoot()",feature)
        self.assertIn("EpochLegacyAutoLootSha",feature)
        self.assertIn("EpochWorkAutoLootRunId",feature)
        self.assertIn('workState["managed_sha256"] = hashes;',feature)
        self.assertIn('EpochInterop.AutoLoot335.dll',wf)
        self.assertIn('GetString(installedEpoch, "module_sha256")',app)
        loader=(ROOT/"src/Loader12340/Wow335Loader.c").read_text(encoding="utf-8")
        self.assertIn("SetWindowsHookExW(WH_GETMESSAGE",loader)
        self.assertIn("WH_CALLWNDPROC",loader)
        self.assertIn("SendMessageTimeoutW(hwnd,message,command",loader)
        self.assertIn("send_control(game.hwnd,message,1u,2000u)",loader)
        self.assertIn("send_control(game.hwnd,message,2u,200u)",loader)
        self.assertNotIn("PostMessageW(game.hwnd,message,2u,0u)",loader)
        self.assertIn("activate_autoloot(autoloot)",loader)
        self.assertIn('L"PULSE_DELIVERED"',loader)
        self.assertIn('L"PULSE_TIMEOUT"',loader)
        self.assertIn("pulses>=250u",loader)
        self.assertNotIn("PrintChat",loader)
        self.assertIn("Kanał STABLE/work nie jest zgodny",app)
        maintenance=(ROOT/"tools/updater/UpdaterMaintenanceFeature.cs").read_text(encoding="utf-8")
        self.assertIn("public static async Task<bool> EnsureCurrentUpdaterAsync(Form form)",maintenance)
        self.assertIn("return await activeController.SelfUpdateAsync();",maintenance)
        self.assertIn("if (UseEpochTestFlow() &&",app)
        self.assertIn("!await MaintenanceFeature.EnsureCurrentUpdaterAsync(this)",app)
        self.assertIn("if (!await MaintenanceFeature.EnsureCurrentUpdaterAsync(this))",app)
        self.assertIn("return false; // newer updater will restart; no premature game launch",app)
        self.assertEqual(interop["final_package"],"NOT_RUN")
        self.assertIn("module_load_order",feature)
        self.assertNotIn("github12wykrzyk/wow112",feature)
        self.assertNotIn("github12wykrzyk/frostmourne",feature)

    def test_empty_runtime_does_not_allow_arbitrary_dll_enumeration(self):
        manifest=json.loads((ROOT/"runtime/current.json").read_text(encoding="utf-8"))
        loader=(ROOT/"src/Loader12340/Wow335Loader.c").read_text(encoding="utf-8")
        self.assertEqual(manifest["files"],[])
        self.assertIn("MANIFEST_CREATED_EMPTY",loader)
        self.assertIn("CREATE_NEW",loader)
        self.assertIn("LOAD_WITH_ALTERED_SEARCH_PATH",loader)
        self.assertIn("DUPLICATE",loader)
        self.assertNotIn("FindFirstFile",loader)

if __name__=="__main__":
    unittest.main()
