"""Regression tests for the feature/loader-12340 updater-only TEST wiring."""
import json
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

class EpochUpdaterTests(unittest.TestCase):
    def test_updater_build_compiles_explicit_epoch_feature(self):
        wf=(ROOT/".github/workflows/build_updater.yml").read_text(encoding="utf-8")
        ui=(ROOT/"tools/updater/Updater335Dashboard.cs").read_text(encoding="utf-8")
        app=(ROOT/"tools/updater/WoW335Updater.cs").read_text(encoding="utf-8")
        feature=(ROOT/"tools/updater/UpdaterEpochLoaderFeature.cs").read_text(encoding="utf-8")
        self.assertIn("feature/loader-12340",wf)
        self.assertIn("src/Loader12340/**",wf)
        self.assertIn("runtime/epoch_loader_interop.json",wf)
        maintenance=(ROOT/"tools/updater/UpdaterMaintenanceFeature.cs").read_text(encoding="utf-8")
        self.assertIn('UpdaterBuildInfo.Version.EndsWith("-epoch-test"',maintenance)
        self.assertIn('"feature/loader-12340"',maintenance)
        self.assertIn("UpdaterEpochLoaderFeature.cs",wf)
        self.assertIn("Epoch Loader TEST",ui)
        self.assertIn("Aktywne DLL / kolejność",ui)
        self.assertIn("Przywróć Epoch DLL",ui)
        self.assertIn("EpochValidateLaunch(root);",app)
        self.assertIn("EpochBranch = \"feature/loader-12340\"",feature)
        self.assertIn("UpdaterSafety.RequireLatestSuccessfulRun",feature)
        self.assertIn("EpochOriginalSha",feature)
        self.assertIn("EpochCheckFile",feature)
        self.assertIn("EpochRollback()",feature)
        self.assertIn("test_pair_gate",feature)
        self.assertIn("module_load_order",feature)
        self.assertIn("EpochExistingManagedOrder",feature)
        self.assertIn("EpochWorkAutoLootCommit",feature)
        self.assertIn("EpochWorkAutoLootSha",feature)
        safety=(ROOT/"tools/updater/UpdaterSafety.cs").read_text(encoding="utf-8")
        self.assertIn("public static bool IsGitCommitSha(string value)",safety)
        self.assertIn("value.Length != 40",safety)
        self.assertIn('UpdaterSafety.IsGitCommitSha(GetString(state, "git_sha"))',feature)
        self.assertIn("UpdaterSafety.IsGitCommitSha(sha)",feature)
        self.assertNotIn("UpdaterSafety.IsSha256Hex(sha)",feature)
        self.assertNotIn('UpdaterSafety.IsSha256Hex(GetString(state, "git_sha"))',feature)
        self.assertIn('UpdaterSafety.IsSha256Hex(GetString(state, "epoch_sha256"))',feature)
        self.assertIn("GitShaSmoke.cs",wf)
        self.assertIn("GIT_SHA_VALIDATION_SMOKE: PASS",wf)
        interop=json.loads((ROOT/"runtime/epoch_loader_interop.json").read_text(encoding="utf-8"))
        self.assertEqual(interop["source"]["commit"],"149a2523f8068e407a8fc74e058b4f24c81d21e5")
        self.assertEqual(interop["source"]["sha256"],"52bc5100d46c6edaa172ab5342d565454ea6629d7a0ec09bafc044f8f0f2b47e")
        self.assertEqual(interop["compatibility"],"not_verified_in_game")
        self.assertIn(interop["source"]["commit"],feature)
        self.assertIn(interop["source"]["sha256"],feature)
        self.assertIn("managed_sha256",feature)
        self.assertIn('GetValue(state, "managed_sha256")',feature)
        self.assertIn('hashValue as Dictionary<string, object>',feature)
        self.assertIn('35855470746L',feature)
        self.assertIn('EpochCheckFile(Path.Combine(root, EpochWorkAutoLoot), EpochWorkAutoLootSha)',feature)
        self.assertIn('string stage = "wstępna kontrola lokalnych plików"',feature)
        self.assertIn('"Etap: " + stage',feature)
        self.assertIn('"artifact_name"',feature)
        self.assertIn("EpochCheckFile(Path.Combine(root, EpochWorkAutoLoot)",feature)
        loader=(ROOT/"src/Loader12340/Wow335Loader.c").read_text(encoding="utf-8")
        self.assertIn("SetWindowsHookExW(WH_GETMESSAGE",loader)
        self.assertIn("PostMessageW(game.hwnd,message,1u,0u)",loader)
        self.assertIn("activate_autoloot(autoloot)",loader)
        self.assertIn("najpierw Przywróć Epoch DLL".lower(),app.lower())
        self.assertEqual(interop["final_package"],"NOT_RUN")
        self.assertIn("module_load_order",feature)
        self.assertNotIn("github12wykrzyk/wow112",feature)
        self.assertNotIn("github12wykrzyk/frostmourne",feature)

    def test_empty_runtime_does_not_allow_arbitrary_dll_enumeration(self):
        manifest=json.loads((ROOT/"runtime/current.json").read_text(encoding="utf-8"))
        loader=(ROOT/"src/Loader12340/Wow335Loader.c").read_text(encoding="utf-8")
        self.assertEqual(manifest["files"],[])
        self.assertIn("MANIFEST_CREATED_EMPTY",loader)
        self.assertIn("CREATE_NEW",loader)
        self.assertIn("LOAD_WITH_ALTERED_SEARCH_PATH",loader)
        self.assertIn("DUPLICATE",loader)
        self.assertNotIn("FindFirstFile",loader)

if __name__=="__main__":
    unittest.main()
